In [1]:
#setup imports and make ure the files we care about exist
%matplotlib inline
import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.data import random_split
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os.path
from pprint import pprint

#custom modules
import feature_extraction
import networks

from importlib import reload #allow us to reload custom modules any time we like with modifications
reload(feature_extraction)
reload(networks)

<module 'networks' from '/home/jaywalker/MachineLearning/PacketGAN/networks.py'>

In [2]:
input_size = 2
sequence_length = 3
hidden_size = 3
batch_size = 5
lsm = networks.GRUMapping(input_size, hidden_size, batch_size)

batched_input = torch.randn(batch_size, sequence_length, input_size)
print("Input shape: ", batched_input.shape)
pprint(batched_input)

lsm_out = lsm(batched_input)
print("lsm out:")
pprint(lsm_out)





Input shape:  torch.Size([5, 3, 2])
tensor([[[ 1.2907, -1.9075],
         [ 0.7907, -1.2057],
         [-0.4468,  1.8102]],

        [[-0.1171, -1.4274],
         [-0.9515,  1.2203],
         [-0.3572,  1.3283]],

        [[-2.3029, -0.6014],
         [ 0.9744, -2.6881],
         [ 0.6822,  0.3435]],

        [[-0.8484,  0.4316],
         [-0.1721,  1.0651],
         [-0.9492, -0.0992]],

        [[ 0.8852, -0.2258],
         [ 0.2451,  0.4645],
         [-1.6962,  0.7825]]])
lsm out:
tensor([[[-0.1132,  0.0111, -0.6473],
         [-0.2769, -0.2434, -0.6836],
         [-0.0773,  0.1870, -0.3005],
         [-0.2832, -0.2586, -0.2867],
         [-0.3092, -0.3199, -0.4601]]], grad_fn=<StackBackward>)


In [3]:
#Try manual batching?
lsm.batch_size = 1

#use same input as previous to compare output
print("Input shape: ", batched_input.shape)
pprint(batched_input)

for e in batched_input:
    enew = torch.tensor([e.numpy()])
    pprint(lsm(enew)) 
    





Input shape:  torch.Size([5, 3, 2])
tensor([[[ 1.2907, -1.9075],
         [ 0.7907, -1.2057],
         [-0.4468,  1.8102]],

        [[-0.1171, -1.4274],
         [-0.9515,  1.2203],
         [-0.3572,  1.3283]],

        [[-2.3029, -0.6014],
         [ 0.9744, -2.6881],
         [ 0.6822,  0.3435]],

        [[-0.8484,  0.4316],
         [-0.1721,  1.0651],
         [-0.9492, -0.0992]],

        [[ 0.8852, -0.2258],
         [ 0.2451,  0.4645],
         [-1.6962,  0.7825]]])
tensor([[[-0.1132,  0.0111, -0.6473]]], grad_fn=<StackBackward>)
tensor([[[-0.2769, -0.2434, -0.6836]]], grad_fn=<StackBackward>)
tensor([[[-0.0773,  0.1870, -0.3005]]], grad_fn=<StackBackward>)
tensor([[[-0.2832, -0.2586, -0.2867]]], grad_fn=<StackBackward>)
tensor([[[-0.3092, -0.3199, -0.4601]]], grad_fn=<StackBackward>)
